/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List positions
         * @description Filter stored lifecycle only. No lifecycle mutation exists.
         */
        get: operations["listJobs"];
        put?: never;
        /**
         * Create position and original JD
         * @description Creates draft lifecycle. Reject whitespace-only title/JD; preserve JD exactly.
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        /**
         * Read workspace context
         * @description Includes readiness from approved criteria, parsed CVs and active run.
         */
        get: operations["getJob"];
        /**
         * Edit position metadata and JD
         * @description Update metadata/JD with optimistic version checks; lifecycle is read-only.
         */
        put: operations["updateJob"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read skill vocabulary
         * @description Read-only dictionary, not an administration API. Does not accept CV text in query parameters.
         */
        get: operations["listSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/criteria-draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        /**
         * Read current unapproved draft
         * @description 404 draft_not_found when no draft; approved revisions use separate endpoints.
         */
        get: operations["getCriteriaDraft"];
        /**
         * Save manual or edited criteria draft
         * @description Save a version-checked draft; incomplete criteria are allowed before approval.
         */
        put: operations["saveCriteriaDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/criteria-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest criteria using GPT-4o mini
         * @description Return validated JD suggestions without saving or approving the draft.
         */
        post: operations["suggestCriteria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/criteria-revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        /**
         * List approved revisions
         * @description Ascending revision order; approved immutable revisions only.
         */
        get: operations["listCriteriaRevisions"];
        put?: never;
        /**
         * Approve current draft as a new revision
         * @description Validate and freeze a new criteria revision atomically; consume the draft.
         */
        post: operations["approveCriteria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/criteria-revisions/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Immutable approved revision number within this position. */
                revision: components["parameters"]["revision"];
            };
            cookie?: never;
        };
        /**
         * Read immutable approved criteria
         * @description Reads original snapshot, never current JD.
         */
        get: operations["getCriteriaRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        /**
         * List candidate identities for version confirmation
         * @description List candidates in this position for explicit new-version upload confirmation.
         */
        get: operations["listPositionCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        /**
         * List accepted CVs and parsing states
         * @description List persisted extraction states, ordered by uploaded_at then resume_id.
         */
        get: operations["listResumes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                resume_id: components["parameters"]["resume_id"];
            };
            cookie?: never;
        };
        /**
         * Read position-scoped CV status
         * @description Includes snapshot ID only after validated extraction. Errors are distinct from eligibility.
         */
        get: operations["getResume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/resume-batches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a PDF/DOCX batch
         * @description Accept a validated batch and report each file outcome; extraction runs asynchronously.
         */
        post: operations["uploadResumeBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/screening-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        /**
         * List run history
         * @description Newest round first. Includes failed/unpublished processing attempts; only published_at != null runs expose results/comparison.
         */
        get: operations["listRuns"];
        put?: never;
        /**
         * Start screening or criteria-only rescore
         * @description Commit one durable screening/rescore command and return its run.
         */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/screening-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
            };
            cookie?: never;
        };
        /**
         * Poll durable progress
         * @description Read persisted progress and publication state; technical failures remain separate.
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/screening-runs/{run_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
            };
            cookie?: never;
        };
        /**
         * Read per-CV progress and technical failures
         * @description Failed items never produce zero scores or rejection decisions. Excludes source text from error payload.
         */
        get: operations["listRunItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/ranking/query": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search/filter a consistent published ranking
         * @description Read a published ranking with run/decision-epoch pagination; search stays in the body.
         */
        post: operations["queryRanking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/screening-runs/{run_id}/results/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
                /** @description Server-issued identifier, validated against parent context. */
                result_id: components["parameters"]["result_id"];
            };
            cookie?: never;
        };
        /**
         * Inspect scores and criterion evidence
         * @description Read snapshot-specific analysis from a published run; validate the full position context.
         */
        get: operations["getResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/screening-runs/{run_id}/results/{result_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
                /** @description Server-issued identifier, validated against parent context. */
                result_id: components["parameters"]["result_id"];
            };
            cookie?: never;
        };
        /**
         * Read safe frozen source preview
         * @description Read plain-text source for evidence; unavailable source returns 503 source_unavailable.
         */
        get: operations["getResultSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/screening-runs/{run_id}/results/{result_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
                /** @description Server-issued identifier, validated against parent context. */
                result_id: components["parameters"]["result_id"];
            };
            cookie?: never;
        };
        /**
         * Read original file for selected result
         * @description Deliver the scoped original PDF/DOCX without exposing private storage paths.
         */
        get: operations["getResultFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/screening-runs/{run_id}/results/{result_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
                /** @description Server-issued identifier, validated against parent context. */
                result_id: components["parameters"]["result_id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Record final shortlist/reject decision
         * @description Record a final decision against the current run/result version; conflicting writes fail.
         */
        patch: operations["recordDecision"];
        trace?: never;
    };
    "/jobs/{job_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        /**
         * Compare two published runs
         * @description Compare two published runs in one position by exact CV snapshot identity.
         */
        get: operations["compareRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/resumes/{resume_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                resume_id: components["parameters"]["resume_id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry failed CV extraction
         * @description Queue extraction only for a parse-failed resume without a validated snapshot.
         */
        post: operations["reprocessResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Positive database bigint encoded as a decimal string to avoid JavaScript precision loss.
         * @example 42
         */
        Id: string;
        /** @example 1 */
        Version: number;
        /**
         * @description Non-negative decimal string; do not use binary floating point for authoritative calculations.
         * @example 92.94
         */
        Decimal: string;
        /** @example 92.94 */
        DisplayedScore: string;
        /**
         * @example {
         *       "code": "stale_result",
         *       "message": "This result changed. Reload it before deciding.",
         *       "request_id": "req-demo-01",
         *       "retryable": false
         *     }
         */
        Error: {
            /** @example stale_result */
            code: string;
            /** @example This result changed. Reload it before deciding. */
            message: string;
            request_id: string;
            details?: {
                field: string;
                code: string;
                message: string;
            }[];
            retryable: boolean;
        };
        /**
         * @example {
         *       "title": "Backend Developer",
         *       "jd_raw_text": "Python is required.",
         *       "level": "Mid"
         *     }
         */
        JobInput: {
            title: string;
            /** @description Non-whitespace original text, preserved exactly. */
            jd_raw_text: string;
            level?: string | null;
        };
        JobUpdate: {
            expected_version: components["schemas"]["Version"];
            title: string;
            jd_raw_text: string;
            level?: string | null;
        };
        Job: {
            id: components["schemas"]["Id"];
            title: string;
            jd_raw_text: string;
            level: string | null;
            status: components["schemas"]["JobStatus"];
            version: components["schemas"]["Version"];
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            criteria_revision: number | null;
            published_run_id: components["schemas"]["NullableId"];
            readiness: {
                approved_criteria: boolean;
                ready_cv_count: number;
                active_run_id: components["schemas"]["NullableId"];
                can_start: boolean;
                blocking_codes: ("criteria_not_approved" | "no_ready_cv" | "active_run")[];
            };
        };
        JobListItem: {
            id: components["schemas"]["Id"];
            title: string;
            level: string | null;
            status: components["schemas"]["JobStatus"];
            created_at: components["schemas"]["Timestamp"];
            ready_cv_count: number;
            published_run_id: components["schemas"]["NullableId"];
            active_run_id: components["schemas"]["NullableId"];
        };
        Page: {
            offset: number;
            limit: number;
            total: number;
        };
        /** @description Exact source evidence with Unicode code-point offsets [start,end). See README section 10 for source identity rules. */
        Evidence: {
            /** @enum {string} */
            source: "jd" | "cv";
            source_id: components["schemas"]["Id"];
            segment_id: string;
            quote: string;
            start_offset: number;
            end_offset: number;
            page: number | null;
            paragraph: number | null;
        };
        CriterionInput: {
            criterion_key: string;
            /** @enum {string} */
            kind: "skill" | "experience" | "education";
            label: string;
            skill_id?: components["schemas"]["NullableId"];
            /** @enum {string} */
            req_type: "mandatory" | "preferred";
            /**
             * @description Draft allows 0; approval requires >0 and exact total 100 across all criteria.
             * @example 92.94
             */
            weight: string;
            min_years?: components["schemas"]["NullableDecimal"];
            /** @enum {string|null} */
            min_degree?: "vocational" | "college" | "bachelor" | "master" | "doctorate" | null;
            /** @enum {string} */
            source: "manual" | "ai";
            jd_evidence?: components["schemas"]["Evidence"][];
        };
        Criterion: {
            id: components["schemas"]["Id"];
            criterion_key: string;
            /** @enum {string} */
            kind: "skill" | "experience" | "education";
            label: string;
            skill_id: components["schemas"]["NullableId"];
            canonical_skill_name: string | null;
            /** @enum {string} */
            req_type: "mandatory" | "preferred";
            weight: components["schemas"]["Decimal"];
            min_years: components["schemas"]["NullableDecimal"];
            /** @enum {string|null} */
            min_degree: "vocational" | "college" | "bachelor" | "master" | "doctorate" | null;
            /** @enum {string} */
            source: "manual" | "ai";
            jd_evidence: components["schemas"]["Evidence"][];
        };
        CriteriaDraftInput: {
            /** @description 0 creates the only active draft; subsequent writes require its current version. */
            expected_draft_version: number;
            /** @description Current approved revision, 0 before first approval. */
            expected_revision: number;
            expected_job_version: components["schemas"]["Version"];
            criteria: components["schemas"]["CriterionInput"][];
        };
        CriteriaDraft: {
            id: components["schemas"]["Id"];
            job_id: components["schemas"]["Id"];
            version: components["schemas"]["Version"];
            base_revision: number;
            job_version: components["schemas"]["Version"];
            jd_snapshot: string;
            criteria: components["schemas"]["Criterion"][];
            updated_at: components["schemas"]["Timestamp"];
        };
        ApprovalInput: {
            expected_draft_version: components["schemas"]["Version"];
            expected_revision: number;
            expected_job_version: components["schemas"]["Version"];
        };
        CriteriaRevision: {
            id: components["schemas"]["Id"];
            job_id: components["schemas"]["Id"];
            revision: components["schemas"]["Version"];
            jd_snapshot: string;
            dictionary_version: string;
            approved_at: components["schemas"]["Timestamp"];
            criteria: components["schemas"]["Criterion"][];
        };
        /** @description Unapproved suggestions only. Missing/ambiguous thresholds are warnings; invalid evidence fails the request. Client merges into draft explicitly. */
        Suggestions: {
            job_id: components["schemas"]["Id"];
            job_version: components["schemas"]["Version"];
            schema_version: string;
            model_version: string;
            criteria: components["schemas"]["CriterionInput"][];
            warnings: string[];
        };
        Candidate: {
            id: components["schemas"]["Id"];
            full_name: string | null;
            email: string | null;
            phone: string | null;
            latest_resume_id: components["schemas"]["Id"];
            latest_version: components["schemas"]["Version"];
        };
        Resume: {
            id: components["schemas"]["Id"];
            job_id: components["schemas"]["Id"];
            candidate_id: components["schemas"]["Id"];
            version: components["schemas"]["Version"];
            file_name: string;
            /** @enum {string} */
            media_type: "application/pdf" | "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
            size_bytes: number;
            status: components["schemas"]["ResumeStatus"];
            snapshot_id: components["schemas"]["NullableId"];
            created_at: components["schemas"]["Timestamp"];
            error_code: string | null;
            can_screen: boolean;
        };
        UploadManifestItem: {
            client_file_id: string;
            file_index: number;
            /** @enum {string} */
            identity_mode: "new_candidate" | "new_version";
            candidate_id?: components["schemas"]["NullableId"];
            identity_confirmed?: boolean;
        };
        /** @description Rejected files have no resume_id. No other-position metadata or raw filenames in messages. */
        UploadOutcome: {
            client_file_id: string;
            /** @enum {string} */
            outcome: "accepted" | "new_version" | "duplicate" | "rejected";
            resume_id: components["schemas"]["NullableId"];
            /** @enum {string|null} */
            status: "uploaded" | "parsing" | "parsed" | "parse_failed" | null;
            error_code: string | null;
            message: string;
        };
        UploadResponse: {
            items: components["schemas"]["UploadOutcome"][];
            accepted_count: number;
            duplicate_count: number;
            rejected_count: number;
        };
        /**
         * @description Initial mode selects resume_ids; rescore selects base_run_id. Cross-field violations return 422; see README section 10.
         * @example {
         *       "mode": "initial",
         *       "criteria_revision": 1,
         *       "resume_ids": [
         *         "21",
         *         "22"
         *       ]
         *     }
         */
        RunInput: {
            /** @enum {string} */
            mode: "initial" | "rescore";
            criteria_revision: components["schemas"]["Version"];
            resume_ids?: components["schemas"]["Id"][];
            base_run_id?: components["schemas"]["Id"];
        };
        /**
         * @example {
         *       "id": "31",
         *       "job_id": "1",
         *       "round": 1,
         *       "mode": "initial",
         *       "base_run_id": null,
         *       "criteria_revision": 1,
         *       "policy_version": "v1",
         *       "status": "queued",
         *       "counts": {
         *         "total": 2,
         *         "pending": 2,
         *         "processing": 0,
         *         "succeeded": 0,
         *         "failed": 0
         *       },
         *       "created_at": "2026-09-16T09:00:00Z",
         *       "started_at": null,
         *       "finished_at": null,
         *       "published_at": null,
         *       "is_current": false,
         *       "error_code": null
         *     }
         */
        Run: {
            id: components["schemas"]["Id"];
            job_id: components["schemas"]["Id"];
            round: components["schemas"]["Version"];
            /** @enum {string} */
            mode: "initial" | "rescore";
            base_run_id: components["schemas"]["NullableId"];
            criteria_revision: components["schemas"]["Version"];
            /** @example v1 */
            policy_version: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "completed_with_errors" | "failed";
            counts: {
                total: number;
                pending: number;
                processing: number;
                succeeded: number;
                failed: number;
            };
            created_at: components["schemas"]["Timestamp"];
            started_at: components["schemas"]["NullableTimestamp"];
            finished_at: components["schemas"]["NullableTimestamp"];
            published_at: components["schemas"]["NullableTimestamp"];
            is_current: boolean;
            error_code: string | null;
        };
        RunItem: {
            resume_id: components["schemas"]["Id"];
            snapshot_id: components["schemas"]["NullableId"];
            /** @enum {string} */
            status: "pending" | "processing" | "succeeded" | "failed";
            attempts: number;
            error_code: string | null;
            error_phase: string | null;
            result_id: components["schemas"]["NullableId"];
        };
        RankRow: {
            result_id: components["schemas"]["Id"];
            resume_id: components["schemas"]["Id"];
            snapshot_id: components["schemas"]["Id"];
            candidate_id: components["schemas"]["Id"];
            candidate_name: string | null;
            file_name: string;
            resume_version: components["schemas"]["Version"];
            rank: number;
            passed_mandatory: boolean;
            displayed_total: components["schemas"]["DisplayedScore"];
            status: components["schemas"]["DecisionStatus"];
            result_version: components["schemas"]["Version"];
            failed_criteria: string[];
            matched_skills: string[];
            missing_skills: string[];
        };
        /** @description No published run returns run_id=null, empty items and zero counts. Failed files are outside ranking. First page pins run_id and decision_epoch for continuation. */
        Ranking: {
            job_id: components["schemas"]["Id"];
            run_id: components["schemas"]["NullableId"];
            criteria_revision: number | null;
            policy_version: string | null;
            is_current: boolean;
            decision_epoch: number;
            active_run_id: components["schemas"]["NullableId"];
            latest_criteria_revision: number | null;
            items: components["schemas"]["RankRow"][];
            page: components["schemas"]["Page"];
            failure_count: number;
            eligibility_counts: {
                passed: number;
                failed: number;
            };
        };
        ResultDetail: {
            id: components["schemas"]["Id"];
            job_id: components["schemas"]["Id"];
            run_id: components["schemas"]["Id"];
            resume_id: components["schemas"]["Id"];
            snapshot_id: components["schemas"]["Id"];
            criteria_revision: components["schemas"]["Version"];
            resume_version: components["schemas"]["Version"];
            candidate: components["schemas"]["SnapshotCandidate"];
            policy_version: string;
            result_version: components["schemas"]["Version"];
            status: components["schemas"]["DecisionStatus"];
            decision_at: components["schemas"]["NullableTimestamp"];
            is_current: boolean;
            can_decide: boolean;
            rank: number;
            passed_mandatory: boolean;
            total_score: components["schemas"]["Decimal"];
            displayed_total: components["schemas"]["DisplayedScore"];
            skill_score: components["schemas"]["NullableDecimal"];
            experience_score: components["schemas"]["NullableDecimal"];
            education_score: components["schemas"]["NullableDecimal"];
            /** @enum {number|null} */
            semantic_score: null;
            summary: string;
            experience: {
                /** @enum {string} */
                normalization_version: "months-v1";
                /** Format: date */
                as_of_date: string;
                supported_months: number;
            };
            criteria: {
                criterion: components["schemas"]["Criterion"];
                /** @enum {string} */
                match_status: "matched" | "partial" | "missing";
                criterion_passed: boolean;
                reason_code: string;
                reason: string;
                score_contribution: components["schemas"]["Decimal"];
                displayed_contribution: components["schemas"]["DisplayedScore"];
                evidence: components["schemas"]["Evidence"][];
            }[];
        };
        /** @description Plain text preview for PDF/DOCX; never executable HTML. Source matches frozen snapshot; no contact details in URL. */
        SourcePreview: {
            resume_id: components["schemas"]["Id"];
            snapshot_id: components["schemas"]["Id"];
            run_id: components["schemas"]["Id"];
            result_id: components["schemas"]["Id"];
            raw_text: string;
            segments: {
                segment_id: string;
                page: number | null;
                paragraph: number | null;
                start_offset: number;
                end_offset: number;
                text: string;
            }[];
        };
        /**
         * @example {
         *       "decision": "shortlisted",
         *       "expected_result_version": 1,
         *       "confirm_failed_mandatory": true
         *     }
         */
        DecisionInput: {
            /** @enum {string} */
            decision: "shortlisted" | "rejected";
            expected_result_version: components["schemas"]["Version"];
            /** @default false */
            confirm_failed_mandatory: boolean;
        };
        Decision: {
            result_id: components["schemas"]["Id"];
            run_id: components["schemas"]["Id"];
            /** @enum {string} */
            status: "shortlisted" | "rejected";
            result_version: components["schemas"]["Version"];
            decision_at: components["schemas"]["Timestamp"];
        };
        ComparisonValue: {
            present: boolean;
            result_id: components["schemas"]["NullableId"];
            rank: number | null;
            /** @example 92.94 */
            displayed_total: string | null;
            passed_mandatory: boolean | null;
            /** @enum {string|null} */
            status: "scored" | "shortlisted" | "rejected" | null;
        };
        /** @description Align exact resume/snapshot identity, never merge by candidate ID. Right minus left deltas; absent side has present=false and all nullable values/deltas null. */
        Comparison: {
            job_id: components["schemas"]["Id"];
            left_run_id: components["schemas"]["Id"];
            right_run_id: components["schemas"]["Id"];
            items: {
                resume_id: components["schemas"]["Id"];
                snapshot_id: components["schemas"]["Id"];
                left: components["schemas"]["ComparisonValue"];
                right: components["schemas"]["ComparisonValue"];
                score_delta: string | null;
                rank_delta: number | null;
                eligibility_changed: boolean | null;
            }[];
            changed_criteria: {
                criterion_key: string;
                /** @enum {string} */
                change: "added" | "removed" | "modified";
                fields: string[];
            }[];
            page: components["schemas"]["Page"];
        };
        Skill: {
            id: components["schemas"]["Id"];
            name: string;
            aliases: string[];
            dictionary_version: string;
        };
        JobList: {
            items: components["schemas"]["JobListItem"][];
            page: components["schemas"]["Page"];
        };
        CandidateList: {
            items: components["schemas"]["Candidate"][];
            page: components["schemas"]["Page"];
        };
        ResumeList: {
            items: components["schemas"]["Resume"][];
            page: components["schemas"]["Page"];
        };
        RunList: {
            items: components["schemas"]["Run"][];
            page: components["schemas"]["Page"];
        };
        RunItemList: {
            items: components["schemas"]["RunItem"][];
            page: components["schemas"]["Page"];
        };
        RevisionList: {
            items: components["schemas"]["CriteriaRevision"][];
            page: components["schemas"]["Page"];
        };
        SkillList: {
            items: components["schemas"]["Skill"][];
            page: components["schemas"]["Page"];
        };
        SuggestionInput: {
            expected_job_version: components["schemas"]["Version"];
        };
        /**
         * @description Body-only search with run/decision-epoch pagination. See README section 10 for page consistency rules.
         * @example {
         *       "run_id": "31",
         *       "decision_epoch": 0,
         *       "offset": 0,
         *       "limit": 50
         *     }
         */
        RankingQuery: {
            run_id?: components["schemas"]["Id"];
            decision_epoch?: number;
            /** @default 0 */
            offset: number;
            /** @default 50 */
            limit: number;
            search?: string;
            passed_mandatory?: boolean;
            decision?: components["schemas"]["DecisionStatus"];
        };
        /** @description Display/contact facts captured for this immutable CV snapshot; never current candidate metadata. */
        SnapshotCandidate: {
            id: components["schemas"]["Id"];
            full_name: string | null;
            email: string | null;
            phone: string | null;
        };
        /**
         * @description Positive database bigint encoded as a decimal string to avoid JavaScript precision loss.
         * @example 42
         */
        NullableId: string | null;
        /**
         * @description Non-negative decimal string; do not use binary floating point for authoritative calculations.
         * @example 92.94
         */
        NullableDecimal: string | null;
        /**
         * Format: date-time
         * @example 2026-09-16T09:00:00Z
         */
        Timestamp: string;
        /**
         * Format: date-time
         * @example 2026-09-16T09:00:00Z
         */
        NullableTimestamp: string | null;
        /** @enum {string} */
        JobStatus: "draft" | "open" | "closed";
        /** @enum {string} */
        DecisionStatus: "scored" | "shortlisted" | "rejected";
        /** @enum {string} */
        ResumeStatus: "uploaded" | "parsing" | "parsed" | "parse_failed";
    };
    responses: {
        /** @description Malformed JSON/multipart, unknown parameter or invalid cursor. */
        400: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource missing or mismatched position/run/result context. Do not disclose other-position existence. */
        404: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Stale version, active run, idempotency mismatch, final decision or changed page snapshot. No conflicting write. */
        409: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description More than 200 files: reject entire batch before acceptance; proxy request too large. */
        413: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unsupported request Content-Type. */
        415: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation or business prerequisite failure. Field errors contain no submitted sensitive values. */
        422: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limited. Retry with backoff and the same idempotency key. */
        429: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected failure; return safe correlation details only. */
        500: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Storage/database/provider temporarily unavailable or request outcome unknown. Retry safely. */
        503: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Successful response. */
        JobResponse: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Job"];
            };
        };
        /** @description Successful response. */
        CriteriaDraftResponse: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CriteriaDraft"];
            };
        };
        /** @description Successful response. */
        CriteriaRevisionResponse: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CriteriaRevision"];
            };
        };
        /** @description Successful response. */
        ResumeResponse: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Resume"];
            };
        };
        /** @description Successful response. */
        RunResponse: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Run"];
            };
        };
    };
    parameters: {
        /** @description Server-issued identifier, validated against parent context. */
        job_id: components["schemas"]["Id"];
        /** @description Server-issued identifier, validated against parent context. */
        resume_id: components["schemas"]["Id"];
        /** @description Server-issued identifier, validated against parent context. */
        run_id: components["schemas"]["Id"];
        /** @description Server-issued identifier, validated against parent context. */
        result_id: components["schemas"]["Id"];
        /** @description Immutable approved revision number within this position. */
        revision: components["schemas"]["Version"];
        /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
        offset: number;
        /** @description Page size. */
        limit: number;
        /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
        key: string;
    };
    requestBodies: never;
    headers: {
        /** @description Required for all responses, including errors and files. */
        CacheControl: "no-store";
        /** @description Correlation ID without sensitive data. */
        XRequestId: string;
        /** @description inline for PDF, attachment for DOCX; safe generic filename without personal data. */
        ContentDisposition: string;
        /** @description Prevent MIME sniffing. */
        XContentTypeOptions: "nosniff";
        /** @description Delay in seconds. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listJobs: {
        parameters: {
            query?: {
                /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
                offset?: components["parameters"]["offset"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
                /** @description Stored lifecycle filter. */
                status?: components["schemas"]["JobStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
                "Idempotency-Key": components["parameters"]["key"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobInput"];
            };
        };
        responses: {
            201: components["responses"]["JobResponse"];
            400: components["responses"]["400"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JobResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    updateJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
                "Idempotency-Key": components["parameters"]["key"];
            };
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            200: components["responses"]["JobResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    listSkills: {
        parameters: {
            query?: {
                /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
                offset?: components["parameters"]["offset"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillList"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    getCriteriaDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CriteriaDraftResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    saveCriteriaDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
                "Idempotency-Key": components["parameters"]["key"];
            };
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriteriaDraftInput"];
            };
        };
        responses: {
            200: components["responses"]["CriteriaDraftResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    suggestCriteria: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
                "Idempotency-Key": components["parameters"]["key"];
            };
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionInput"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestions"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    listCriteriaRevisions: {
        parameters: {
            query?: {
                /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
                offset?: components["parameters"]["offset"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionList"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    approveCriteria: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
                "Idempotency-Key": components["parameters"]["key"];
            };
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalInput"];
            };
        };
        responses: {
            201: components["responses"]["CriteriaRevisionResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    getCriteriaRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Immutable approved revision number within this position. */
                revision: components["parameters"]["revision"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CriteriaRevisionResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    listPositionCandidates: {
        parameters: {
            query?: {
                /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
                offset?: components["parameters"]["offset"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateList"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    listResumes: {
        parameters: {
            query?: {
                /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
                offset?: components["parameters"]["offset"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
                /** @description Optional parse status. */
                status?: components["schemas"]["ResumeStatus"];
            };
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeList"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    getResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                resume_id: components["parameters"]["resume_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ResumeResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    uploadResumeBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
                "Idempotency-Key": components["parameters"]["key"];
            };
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                    manifest: components["schemas"]["UploadManifestItem"][];
                };
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            413: components["responses"]["413"];
            415: components["responses"]["415"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
                offset?: components["parameters"]["offset"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
                /** @description Only successfully published history. */
                published_only?: boolean;
            };
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
                "Idempotency-Key": components["parameters"]["key"];
            };
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunInput"];
            };
        };
        responses: {
            202: components["responses"]["RunResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RunResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    listRunItems: {
        parameters: {
            query?: {
                /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
                offset?: components["parameters"]["offset"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
                /** @description Filter failures separately from ranking. */
                status?: "pending" | "processing" | "succeeded" | "failed";
            };
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunItemList"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    queryRanking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingQuery"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ranking"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    getResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
                /** @description Server-issued identifier, validated against parent context. */
                result_id: components["parameters"]["result_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultDetail"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    getResultSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
                /** @description Server-issued identifier, validated against parent context. */
                result_id: components["parameters"]["result_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePreview"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    getResultFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
                /** @description Server-issued identifier, validated against parent context. */
                result_id: components["parameters"]["result_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private original CV bytes. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Content-Disposition": components["headers"]["ContentDisposition"];
                    "X-Content-Type-Options": components["headers"]["XContentTypeOptions"];
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    recordDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                run_id: components["parameters"]["run_id"];
                /** @description Server-issued identifier, validated against parent context. */
                result_id: components["parameters"]["result_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    compareRuns: {
        parameters: {
            query: {
                /** @description Zero-based offset. Non-ranking collections are live and may change between requests. */
                offset?: components["parameters"]["offset"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
                /** @description Baseline published run. */
                left_run_id: components["schemas"]["Id"];
                /** @description Compared published run. */
                right_run_id: components["schemas"]["Id"];
            };
            header?: never;
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
    reprocessResume: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated opaque key scoped to operation and position. Same normalized payload returns same outcome; changed payload is 409. Never include personal data. */
                "Idempotency-Key": components["parameters"]["key"];
            };
            path: {
                /** @description Server-issued identifier, validated against parent context. */
                job_id: components["parameters"]["job_id"];
                /** @description Server-issued identifier, validated against parent context. */
                resume_id: components["parameters"]["resume_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["ResumeResponse"];
            400: components["responses"]["400"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
            503: components["responses"]["503"];
        };
    };
}
